#Each new term in the Fibonacci sequence
# is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence
# whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib(n):
    a = 1
    b = 1
    while b <= n:
        yield b
        a, b = b, a+b

def sol_2a(n):
    num = 0
    for f in fib(n):
        if f % 2 == 0:
            num += f
    return num

def sol_2b(n):
    a = 1
    b = 2
    num = 0
    while b <= n:
        num += b
        a, b = b, a + b
        a, b = b, a + b
        a, b = b, a + b
    return num